### ISSUE TITLE
Mixed data structure with hashes that have keys with values that are JSON encoded

### ISSUE THREAD

**Issue by helperton** [spaceghoul/json_deep_parse#1]
Wondering if I can use json_deep_parse to handle this situation?

`{:error=>true, :code=>403, :message=>"Request d9c91c0097f9c5184b7e355e6253afd4 already exists!", :data=>{:request_exists=>true, :payload=>{:tag=>"tag", :distro_series=>"distro", :amount=>"1", :interface_set=>"[{\"type\":\"bond\",\"bond_type\":\"balance-tlb\",\"interfaces\":[\"ens1f0\",\"eno5\"],\"context\":\"TEST\"},{\"type\":\"bond\",\"bond_type\":\"balance-tlb\",\"interfaces\":[\"ens1f0\",\"eno5\"],\"context\":\"NET\"}]", :storage_set=>"[{\"type\":\"hardware\",\"raid_type\":\"5\"}]", :application_service=>"app", :id=>"4561c0097f9c5184b7e355e6253afd4"}}}`

Where object[:data][:payload][:interface_set] and [:storage_set] are JSON encoded, but the rest is not.

**Comment by bnbry** [comment]
I want to apologize, I'm sure this response is far too late to be useful.

Out of the box, it wasn't intended to parse objects that weren't already JSON strings at the highest level but it technically would work.  You have two options.

A) You could convert the hash to JSON first, then deeply parse it.

```ruby 
  using ::JSONDeepParse

  # JSON.dump or some form of to_json/as_json if you are in Rails
  now_its_json = JSON.dump(your_hash_with_nested_json)
  JSON.deep_parse(now_its_json)
```

B) Since this refines Hash to have a `deep_parse` method you could just call that directly on the hash and it should work.

```ruby
  using ::JSONDeepParse

  your_hash_with_nested_json.deep_parse
```
